<?php


namespace App\Command;


use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class GetSocieteBySiretCommand extends Command
{
    protected static $defaultName = 'app:get-society';

    protected function configure()
    {
      $this->setDescription('Récupérer les infos d\'une societe en rentrant son n°siret')
            ->addArgument('siret', InputArgument::REQUIRED, 'n°siret');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent ::execute($input, $output); // TODO: Change the autogenerated stub
    }

}